//
//  Event.swift
//  Hashtag Generator Pro
//
//  Created by Karan Chilwal on 14/06/24.
//

import Foundation

enum AmplitudeEvents: String {
        case first_app_launch = "first_app_launch"
        case tracking_not_allow = "tracking_not_allow"
        case tracking_allow = "tracking_allow"
        case intro_get_started = "intro_get_started"
        case onboarding_next = "onboarding_next"
        case paywall_annual = "paywall_annual"
        case paywall_weekly = "paywall_weekly"
        case paywall_start_plan = "paywall_start_plan"
        case paywall_plan_cancelled_ = "paywall_plan_cancelled_"
        case paywall_plan_errored_ = "paywall_plan_errored_"
        case paywall_plan_subscribed_ = "paywall_plan_subscribed_"
        case paywall_restore = "paywall_restore"
        case paywall_terms = "paywall_terms"
        case paywall_cross = "paywall_cross"
        case setup_goto_settings = "setup_goto_settings"
        case setup_whatis_fa = "setup_whatis_fa"
        case setup_cross = "setup_cross"
        case home_settings = "home_settings"
        case home_setup = "home_setup"
        case home_pro = "home_pro"
        case home_email_writer = "home_email_writer"
        case home_ask_ai = "home_ask_ai"
        case home_howcan_iuse = "home_howcan_iuse"
        case reply_tutorial_send = "reply_tutorial_send"
        case reply_tutorial_next = "reply_tutorial_next"
        case reply_tutorial_cross = "reply_tutorial_cross"
        case settings_keyboard_status = "settings_keyboard_status"
        case settings_pro = "settings_pro"
        case settings_feature_order = "settings_feature_order"
        case settings_sound = "settings_sound"
        case settings_haptic = "settings_haptic"
        case settings_share = "settings_share"
        case settings_like_rate = "settings_like_rate"
        case settings_about_zv = "settings_about_zv"
        case settings_faq = "settings_faq"
        case settings_request_feature = "settings_request_feature"
        case settings_give_feedback = "settings_give_feedback"
        case settings_restore_purchases = "settings_restore_purchases"
        case settings_manage_subscription = "settings_manage_subscription"
        case settings_privacy_policy = "settings_privacy_policy"
        case settings_terms = "settings_terms"
        case faq_query = "faq_query"
        case faq_contactus = "faq_contactus"
        case email_change_ol_ = "email_change_ol_"
        case email_change_tf_ = "email_change_tf_"
        case email_write_submit = "email_write_submit"
        case ask_ai_submit = "ask_ai_submit"
        case email_reply_changestatus_ = "email_reply_changestatus_"
        case email_reply_submit = "email_reply_submit"
        case email_output_rewrite = "email_output_rewrite"
        case email_output_copy = "email_output_copy"
        case email_output_share = "email_output_share"
        case keyboard_activated = "keyboard_activated"
        case keyboard_full_accessed = "keyboard_full_accessed"
        
        case activation_notification_scheduled_ = "activation_notification_scheduled_"
        case activation_notification_shown_ = "activation_notification_shown_"
        case activation_notification_tap_ = "activation_notification_tap_"
        case activation_watch_settings_issue = "activation_watch_settings_issue"
        case activation_watch_setup_issue = "activation_watch_setup_issue"
        case activation_email = "activation_email"
        case activation_cross = "activation_cross"
        case activation_goto_settings = "activation_goto_settings"
        case activation_watch_goto_settings = "activation_watch_goto_settings"
    
        case notification_allowed = "notification_allowed"
        case notification_not_allowed = "notification_not_allowed"
    
        case extn_learn_more_tap = "extn_learn_more_tap"
        case extn_logo_tap = "extn_logo_tap"
        case extn_cross_tap = "extn_cross_tap"
        case extn_nps_tap = "extn_nps_tap"
        case extn_rating_cross_tap = "extn_rating_cross_tap"
        case extn_rating_tap = "extn_rating_tap"
        case extn_grammar_tap = "extn_grammar_tap"
        case extn_grammar_apply = "extn_grammar_apply"
        case extn_grammar_regen = "extn_grammar_regen"
        case extn_askai_tap = "extn_askai_tap"
        case extn_askai_apply = "extn_askai_apply"
        case extn_askai_regen = "extn_askai_regen"
        case extn_askai_chat_tap = "extn_askai_chat_tap"
        case extn_emojify_tap = "extn_emojify_tap"
        case extn_emojify_apply = "extn_emojify_apply"
        case extn_emojify_regen = "extn_emojify_regen"
        case extn_reply_tap = "extn_reply_tap"
        case extn_reply_apply = "extn_reply_apply"
        case extn_reply_regen = "extn_reply_regen"
        case extn_tone_tap = "extn_tone_tap"
        case extn_tone_changetone_ = "extn_tone_changetone_"
        case extn_tone_apply = "extn_tone_apply"
        case extn_tone_regen = "extn_tone_regen"
        case extn_translate_tap = "extn_translate_tap"
        case extn_translate_change_language_ = "extn_translate_change_language_"
        case extn_translate_apply = "extn_translate_apply"
        case extn_translate_regen = "extn_translate_regen"
        case extn_paraphrase_tap = "extn_paraphrase_tap"
        case extn_paraphrase_apply = "extn_paraphrase_apply"
        case extn_paraphrase_regen = "extn_paraphrase_regen"
        case extn_synonym_tap = "extn_synonym_tap"
        case extn_synonym_apply = "extn_synonym_apply"
        case extn_synonym_regen = "extn_synonym_regen"
        case extn_continue_tap = "extn_continue_tap"
        case extn_continue_apply = "extn_continue_apply"
        case extn_continue_regen = "extn_continue_regen"
        case extn_email_tap = "extn_email_tap"
        case extn_ask_ai_tap = "extn_ask_ai_tap"
        case extn_setting_tap = "extn_setting_tap"
        case extn_emoji_tap = "extn_emoji_tap"
        case extn_keyboard_ = "extn_keyboard_"
        case extn_keyboard_enabled = "extn_keyboard_enabled"
}
